version: '3.9'
services:
  premier-league-mvc:
    image:
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - premier-league-db
    environment:
      - PORT=3000
      - DB_USER=postgres
      - DB_HOST=premier-league-db
      - DB_NAME=premier-league
      - DB_PASSWORD=docker
      - DB_PORT=5432

    networks:
      - premier-league-network

  premier-league-db:
    image: 
    ports:
      - "5432:5432"
    restart: always
    networks:
      - premier-league-network
      
networks:
  premier-league-network: